---
title: "Untitled"
author: "Benjamin Arthur"
date: "2022-11-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
 

library(singlet)
library(ggplot2)
library(dplyr)
library(cowplot)
library(vegan)
pbmc3k <- get_pbmc3k_data()
pbmc3k <- pbmc3k %>% NormalizeData() %>% RunNMF(reps = 1)

cell = c("AACCGCCTCTACGAA","AACCTACTGTGAGG","AACCAGTGATACCG","AACACGTGGAAAGT")

pbmc3k <- RescaleNMF(pbmc3k,features=cell,reduction="nmf",lambda=0.8,reduction.name="nmf_rescaled")
model_reference <- RunUMAP(pbmc3k, reduction = "nmf", reduction.name = "umap_nmf", dims = 1:ncol(pbmc3k@reductions$nmf@cell.embeddings))

model_reference@reductions$umap_nmf@cell.embeddings
model_query <- RunUMAP(pbmc3k, reduction = "nmf_rescaled", reduction.name = "umap_nmf_rescaled", dims = 1:ncol(pbmc3k@reductions$nmf_rescaled@cell.embeddings))
```

```{r}
set.seed(542)
# Cell.embedding
cell = c("AACCGCCTCTACGAA","AACCTACTGTGAGG","AACCAGTGATACCG","AACACGTGGAAAGT")

pbmc3k <- RescaleNMF(pbmc3k,features=cell,reduction="nmf",lambda=0.8,reduction.name="nmf_rescaled")

model_reference <- RunUMAP(pbmc3k, reduction = "nmf", reduction.name = "umap_nmf", dims = 1:ncol(pbmc3k@reductions$nmf@cell.embeddings))

model_query <- RunUMAP(pbmc3k, reduction = "nmf_rescaled", reduction.name = "umap_nmf_rescaled", dims = 1:ncol(pbmc3k@reductions$nmf_rescaled@cell.embeddings))

plot_grid(DimPlot(model_reference, reduction = "umap_nmf", group.by = "cell_type"), DimPlot(model_query, reduction = "umap_nmf_rescaled", group.by = "cell_type"), ncol = 2)


X <- as.matrix(cbind(model_reference@reductions$umap_nmf$UMAP_1,model_reference@reductions$umap_nmf$UMAP_2))

X<-as.matrix(cbind(nov$longitude,nov$latitude))

library(singlet)

```

```{r}
data(varespec)
vare.dist <- vegdist(wisconsin(varespec))
mds.null <- monoMDS(vare.dist, y = cmdscale(vare.dist))
mds.alt <- monoMDS(vare.dist)
vare.proc <- procrustes(mds.alt, mds.null)
vare.proc

mds.alt$
```

```{r}

library(MCMCpack)
library(maps)
nov<-read.table("PCA.txt",header=TRUE,sep="\t")
X<-as.matrix(cbind(nov$longitude,nov$latitude))
Xstar<-as.matrix(cbind(nov$PC1,nov$PC2))
p<-procrustes(Xstar,X,translation=TRUE,dilation=TRUE)
map(database="world",regions=c('belgium','netherlands',
'austria','denmark','portugal','italy','spain','uk','germany',
'france','sweden','norway','finland','luxemburg',
'greece','monaco','ireland'),xlim=c(-10,20),ylim=c(35,60))
map.axes()
text(p$X.new,col=c(nov$alabels),labels=nov$alabels,cex=0.45)
text(nov$longitude,nov$latitude,col=c(nov$alabels),
labels=nov$alabels)
```

```{r}
library(tidyverse)
library(singlet)
library(Seurat)
library(msigdbr)
library(readr)
library(qusage)

msigdbr_species()
m_df = msigdbr(species = "Homo sapiens")
m_df <- cbind(Row.Names = rownames(m_df),m_df)


seu_m <- CreateSeuratObject(counts = m_df,min.cells = 0)
seu_m <- seu_m%>% NormalizeData()%>% RunNMF(reps = 1)
seu_m@meta.data
seu_m@meta.data

pbmc3k <- pbmc3k %>% NormalizeData() %>% RunNMF(reps = 1)
df<- read_tsv('gopb.tsv',col_names = TRUE)
dff <-df %>%
  separate_rows(STANDARD_NAME,sep =',')%>%
  separate_rows(GOBP_CANONICAL_WNT_SIGNALING_PATHWAY, sep = ',')

dff[335:644,]


print(df)
```

```{r}


library(singlet)
library(ggplot2)
library(dplyr)
library(cowplot)
library(vegan)
pbmc3k <- get_pbmc3k_data()
pbmc3k <- pbmc3k %>% NormalizeData() %>% RunNMF(reps = 1)

cell = c("AACCGCCTCTACGAA","AACCTACTGTGAGG","AACCAGTGATACCG","AACACGTGGAAAGT")

pbmc3k <- RescaleNMF(pbmc3k,features=cell,reduction="nmf",lambda=0.8,reduction.name="nmf_rescaled")
model_reference <- RunUMAP(pbmc3k, reduction = "nmf", reduction.name = "umap_nmf", dims = 1:ncol(pbmc3k@reductions$nmf@cell.embeddings))

model_reference@reductions$umap_nmf@cell.embeddings

model_query <- RunUMAP(pbmc3k, reduction = "nmf_rescaled", reduction.name = "umap_nmf_rescaled", dims = 1:ncol(pbmc3k@reductions$nmf_rescaled@cell.embeddings))




procrustes <-
  function (object_X, object_Y, scale = TRUE, reduction_X="umap_nmf",reduction_Y="umap_nmf_rescaled",symmetric = FALSE,reduction.name="umap_nmf_procrustes",...)
  {
    
    X_model <- object_X@reductions[[reduction_X]]
    Y_model <- object_Y@reductions[[reduction_Y]]
    X <- X_model@cell.embeddings
    Y <- Y_model@cell.embeddings
    #X <- scores(X, display = scores, ...)
    #Y <- scores(Y, display = scores, ...)
    if (nrow(X) != nrow(Y))
      stop(gettextf("matrices have different number of rows: %d and %d",
                    nrow(X), nrow(Y)))
    if (ncol(X) < ncol(Y)) {
      warning("X has fewer axes than Y: X adjusted to comform Y\n")
      addcols <- ncol(Y) - ncol(X)
      for (i in 1:addcols) X <- cbind(X, 0)
    }
    ctrace <- function(MAT) sum(MAT^2)
    c <- 1
    if (symmetric) {
      X <- scale(X, scale = FALSE)
      Y <- scale(Y, scale = FALSE)
      X <- X/sqrt(ctrace(X))
      Y <- Y/sqrt(ctrace(Y))
    }
    xmean <- apply(X, 2, mean)
    ymean <- apply(Y, 2, mean)
    if (!symmetric) {
      X <- scale(X, scale = FALSE)
      Y <- scale(Y, scale = FALSE)
    }
    XY <- crossprod(X, Y)
    sol <- svd(XY)
    A <- sol$v %*% t(sol$u)
    if (scale) {
      c <- sum(sol$d)/ctrace(Y)
    }
    Yrot <- c * Y %*% A
    colnames(Yrot) <- c('UMAP_1','UMAP_2')

    Y_model@cell.embeddings = as.matrix(Yrot)
    object_Y@reductions[[reduction.name]] <- Y_model
    object_Y
    }

    nmf_model@cell.embeddings <- as.matrix(h %*% Matrix::Diagonal(x=v))
    object@reductions[[reduction.name]] <- nmf_model
    object 

 
SS <- procrustes(model_reference,model_query)

dd <-procrustes(model_reference@reductions$umap_nmf@cell.embeddings,model_query@reductions$umap_nmf@cell.embeddings)


  

colnames(dd$Yrot) <- c('UMAP_1','UMAP_2')
new_y <-dd$Yrot
model_reference@reductions$umap_nmf@cell.embeddings <- new_y
model_reference@reductions$

plot_grid(DimPlot(model_reference, reduction = "umap_nmf", group.by = "cell_type"), DimPlot(model_query, reduction = "umap_nmf_rescaled", group.by = "cell_type"), ncol = 2)



```







