---
title: "Guided Clustering with NMF"
author: "Zach DeBruine"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Guided Clustering with NMF}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This vignette complements the [Seurat Guided Clustering](https://satijalab.org/seurat/articles/pbmc3k_tutorial.html) tutorial, but using NMF and `singlet` instead.

## Set up the Seurat object

This vignette introduces guided clustering and basic gene set enrichment analysis using `singlet` and `Seurat`. It uses the `SeuratData::pbmc3k` dataset and overlaps with the Seurat introductory tutorial on [guided clustering] (satijalab.org/seurat/articles/pbmc3k_tutorial.html) using the `SeuratData::pbmc3k` dataset.

```{R, message = FALSE, warning = FALSE, get-started}
library(singlet)
library(Seurat)
library(dplyr)
library(ggplot2)
pbmc3k <- singlet::get_pbmc3k_data()
```

## Run NMF

NMF can be run on all features using normalized counts. Here we apply standard log-normalization, which works very well, but any form of approximate variance stabilizing transformation is suitable for helping NMF find meaningful solutions. Raw counts are not suitable for NMF because the model pays too much attention to features with very high counts.

`RunNMF` will automatically run cross-validation on an array of ranks that you provide, identify the best rank, and learn a model at that rank. 

Cross-validation can take some time. For large datasets, it is useful to start with a coarse-grained scan of a wide range of ranks and then focus on a narrow window of ranks with several replicates. Remember that the optimal number of NMF factors in your analysis may be significantly greater than the number of PCA components that might be used.  This is a great step to run on a High Performance Computing node.

First off, basic quality control:

```{R, message = FALSE, warning = FALSE, results = 'hide', quality-control}
pbmc3k[["percent.mt"]] <- PercentageFeatureSet(pbmc3k, pattern = "^MT-")
pbmc3k <- subset(pbmc3k, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)
```

Now run NMF cross-validation and learn the model at the (automatically determined) best rank, then annotate the model with available metadata, which in this case is cell types:

```{R, results = 'hide', message = FALSE, warning = FALSE, cross-validation}
set.seed(123)
pbmc3k <- PreprocessData(pbmc3k) %>% RunNMF() %>% AnnotateNMF()
```

Remember to set the seed, as above, to guarantee reproducibility of your NMF model.

Plot the cross-validation results:

```{R}
RankPlot(pbmc3k)
```

You can also look at the iteration-level results:

```{R}
RankPlot(pbmc3k, detail = 2)
```

Plot the annotation results for `cell_type`, since `cell_type` is a factor in the `@meta.data` slot of the Seurat object:

```{R}
AnnotationPlot(pbmc3k)
```

## Visualization

Plot the representation of various metadata (i.e. Seurat-annotated cell types) in each factor:

```{R, fig.width = 5, fig.height = 3, plot-metadata}
MetadataPlot(pbmc3k, "cell_type", reduction = "nmf")
```

Here we simply do what the Seurat Guided Clustering tutorial does, but for NMF:

```{R, fig.width = 5, fig.height = 5, viz-dim-loadings}
VizDimLoadings(pbmc3k, dims = 1:2, reduction = "nmf")
```

## Gene Set Enrichment Analysis

`singlet` makes GSEA with `fgsea` and `msigdbr` easy. Simply, the weights in the NMF "w" matrix are used as rankings for terms in the enrichment analysis.

```{R, message = FALSE, warning = FALSE, results = 'hide', gsea}
pbmc3k <- RunGSEA(pbmc3k, category = "C7", verbose = FALSE)
```

<details>

  <summary>See how GSEA results are stored in the NMF model:</summary>

```{R, echo = FALSE, gsea-data-structure}
str(pbmc3k@reductions$nmf)
```

</details>


`singlet` provides a helper function for quick exploration of GSEA results:

```{R, fig.width = 7, fig.height = 7, gsea-heatmap}
GSEAHeatmap(pbmc3k, reduction = "nmf", max.terms.per.factor = 3)
```

## Cell Clustering

The `pbmc3k` dataset ships with clusters that have been determined by graph-based clustering on a PCA embedding, followed by annotation based on cluster marker genes.

We will determine clusters by graph-based clustering on an NMF embedding, and then compare them to the PCA-guided clustering.

```{R, message = FALSE, warning = FALSE, results = 'hide', cluster-cells}
pbmc3k <- FindNeighbors(pbmc3k, dims = 1:ncol(pbmc3k@reductions$nmf), reduction = "nmf") %>%
  FindClusters(resolution = 0.5, verbose = FALSE) %>%
  RunUMAP(reduction = "nmf", dims = 1:ncol(pbmc3k@reductions$nmf), verbose = FALSE)
```

Because NMF factors are additive signals, we can also visualize their representation on UMAP coordinates:

```{R, fig.width =7, fig.height = 8, feature-plot}
FeaturePlot(pbmc3k, features = paste0("NMF_", 1:6))
```

Compare the composition of NMF clusters to Seurat PCA-guided clustering:

```{R, fig.width = 5, fig.height = 3, map-cluster-ids}
df <- data.frame(
  "nmf_clusters" = pbmc3k@meta.data$seurat_clusters,
  "pca_clusters" = pbmc3k@meta.data$cell_type)

df <- df[!is.na(df$pca_clusters), ]

df <- df %>% 
  group_by(nmf_clusters) %>% 
  count(pca_clusters) %>% 
  mutate(freq = n / sum(n))

ggplot(df, aes(nmf_clusters, pca_clusters, size = freq, color = n)) + 
  geom_point() + 
  theme_bw() + 
  labs(x = "NMF cluster", 
       y = "PCA cluster", 
       size = "proportion\nof cluster", 
       color = "cells in\nNMF cluster") + 
  scale_color_viridis_c(option = "D")
```

Since there is significant correspondence between PCA- and NMF-guided clusters, we can just transfer the labels based on majority overlap:

```{R, fig.width = 5, fig.height = 5, dim-plot}
cluster_names <- df %>% 
  slice(which.max(n)) %>% 
  pull(pca_clusters)

levels(pbmc3k@meta.data$seurat_clusters) <- make.unique(as.vector(cluster_names))

DimPlot(pbmc3k, 
        reduction = "umap", 
        label = TRUE, 
        group.by = "seurat_clusters", 
        pt.size = 0.5) + NoLegend()
```

Compared to the PCA clustering (see the Seurat vignette), the NMF clustering more completely resolves NK cells and better resolves CD8 T-cells from Memory CD4 T-cells, but does not identify a small cluster of Dendritic Cells annotated in the Seurat vignette.

These results show how PCA and NMF can be used to achieve very similar results for cell clustering, while NMF models are interpretable and capture more information and thus better cluster resolution.