# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

weight_by_split <- function(A_, split_by, n_groups) {
    .Call(`_singlet_weight_by_split`, A_, split_by, n_groups)
}

c_nmf <- function(A, At, tol, maxit, verbose, L1, L2, threads, w, link_h, link_w, seed, inv_density) {
    .Call(`_singlet_c_nmf`, A, At, tol, maxit, verbose, L1, L2, threads, w, link_h, link_w, seed, inv_density)
}

