# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

weight_by_split <- function(A_, split_by, n_groups) {
    .Call(`_singlet_weight_by_split`, A_, split_by, n_groups)
}

rowwise_compress_sparse <- function(A, n = 10L, threads = 0L) {
    .Call(`_singlet_rowwise_compress_sparse`, A, n, threads)
}

rowwise_compress_dense <- function(A, n = 10L, threads = 0L) {
    .Call(`_singlet_rowwise_compress_dense`, A, n, threads)
}

c_project_model <- function(A, w, L1, L2, threads) {
    .Call(`_singlet_c_project_model`, A, w, L1, L2, threads)
}

c_nmf <- function(A, At, tol, maxit, verbose, L1, L2, threads, w) {
    .Call(`_singlet_c_nmf`, A, At, tol, maxit, verbose, L1, L2, threads, w)
}

c_nmf_sparse_list <- function(A_, At_, tol, maxit, verbose, L1, L2, threads, w) {
    .Call(`_singlet_c_nmf_sparse_list`, A_, At_, tol, maxit, verbose, L1, L2, threads, w)
}

write_IVCSC <- function(L, verbose = TRUE) {
    .Call(`_singlet_write_IVCSC`, L, verbose)
}

save_IVSparse <- function(A_, verbose = TRUE) {
    .Call(`_singlet_save_IVSparse`, A_, verbose)
}

build_IVCSC2 <- function(L, verbose = TRUE) {
    .Call(`_singlet_build_IVCSC2`, L, verbose)
}

read_IVSparse <- function() {
    .Call(`_singlet_read_IVSparse`)
}

run_nmf_on_sparsematrix_list <- function(A_, tol, maxit, verbose, threads, w, use_vcsc = FALSE) {
    .Call(`_singlet_run_nmf_on_sparsematrix_list`, A_, tol, maxit, verbose, threads, w, use_vcsc)
}

c_mu_nmf <- function(A, At, tol, maxit, verbose, L1, L2, threads, w) {
    .Call(`_singlet_c_mu_nmf`, A, At, tol, maxit, verbose, L1, L2, threads, w)
}

c_nmf_dense <- function(A, At, tol, maxit, verbose, L1, L2, threads, w) {
    .Call(`_singlet_c_nmf_dense`, A, At, tol, maxit, verbose, L1, L2, threads, w)
}

c_linked_nmf <- function(A, At, tol, maxit, verbose, L1, L2, threads, w, link_h, link_w) {
    .Call(`_singlet_c_linked_nmf`, A, At, tol, maxit, verbose, L1, L2, threads, w, link_h, link_w)
}

c_ard_nmf <- function(A, At, tol, maxit, verbose, L1, L2, threads, w, seed, inv_density, overfit_threshold, trace_test_mse) {
    .Call(`_singlet_c_ard_nmf`, A, At, tol, maxit, verbose, L1, L2, threads, w, seed, inv_density, overfit_threshold, trace_test_mse)
}

c_ard_nmf_sparse_list <- function(A_, At_, tol, maxit, verbose, L1, L2, threads, w, rng_seed, inv_density, overfit_threshold, trace_test_mse) {
    .Call(`_singlet_c_ard_nmf_sparse_list`, A_, At_, tol, maxit, verbose, L1, L2, threads, w, rng_seed, inv_density, overfit_threshold, trace_test_mse)
}

c_ard_nmf_dense <- function(A, At, tol, maxit, verbose, L1, L2, threads, w, seed, inv_density, overfit_threshold, trace_test_mse) {
    .Call(`_singlet_c_ard_nmf_dense`, A, At, tol, maxit, verbose, L1, L2, threads, w, seed, inv_density, overfit_threshold, trace_test_mse)
}

spatial_graph <- function(c1, c2, max_dist, max_k = 100L, threads = 0L) {
    .Call(`_singlet_spatial_graph`, c1, c2, max_dist, max_k, threads)
}

c_LKNN <- function(m, coord_x, coord_y, k, radius, metric, similarity, max_dist, verbose, threads) {
    .Call(`_singlet_c_LKNN`, m, coord_x, coord_y, k, radius, metric, similarity, max_dist, verbose, threads)
}

c_SNN <- function(G, min_similarity, threads) {
    .Call(`_singlet_c_SNN`, G, min_similarity, threads)
}

c_gcnmf <- function(A, At, G, tol, maxit, verbose, L1, L2, threads, w) {
    .Call(`_singlet_c_gcnmf`, A, At, G, tol, maxit, verbose, L1, L2, threads, w)
}

c_differentiate_model <- function(h, G) {
    .Call(`_singlet_c_differentiate_model`, h, G)
}

c_assign_cells_to_edge_clusters <- function(G, h_diff_clusters) {
    .Call(`_singlet_c_assign_cells_to_edge_clusters`, G, h_diff_clusters)
}

